### ISSUE TITLE
[DOCS] Addition of a resource in YAML

### ISSUE THREAD

**Issue by n0rdd3v** [Pradumnasaraf/DevOps#101]
### Description

Hey,

 I would like to add a YAML resource to the documentation.

Link to resource => https://yamline.com/ (Formatter, Validator, Comparator, Converters)

**Comment by Pradumnasaraf** [comment]
Oh, that is an awesome resource. Feel free to add that.

Thanks for rasing an issue

**Comment by Pradumnasaraf** [comment]
Hey, Are you sending a PR?

**Comment by n0rdd3v** [comment]
> Hey, Are you sending a PR?

Sorry, I missed the notification.

PR: https://github.com/Pradumnasaraf/DevOps/pull/103

**Comment by Pradumnasaraf** [comment]
Looks good! Thank you!
