### ISSUE TITLE
[DOCS] Addition of a resources in GitHub Action

### ISSUE THREAD

**Issue by iriteshmishra** [Pradumnasaraf/DevOps#105]
### Description

I would like to add one Github Action resource to the documentation from the place I have learned Github Action

Link to resource => [Github Actions Certification](https://youtu.be/Tz7FsunBbfQ?si=U0kXv2qBptdB1QYS)

**Comment by Pradumnasaraf** [comment]
Hey,

Please read the contributing guidelines before opening the Pull Request. 

>Pull Requests having no issue associated with them will not be accepted. Firstly get an issue assigned, whether it's already opened or raised by you, and then create a Pull Request.

**Comment by iriteshmishra** [comment]
Sry for that can you assign me this issue?

**Comment by Pradumnasaraf** [comment]
It's already merged!

Closes #106
