### ISSUE TITLE
[BUG] #/Kubernetes/YAML Not working

### ISSUE THREAD

**Issue by heykush** [Pradumnasaraf/DevOps#12]
### Description

This [#/Kubernetes/YAML](https://pradumnasaraf.dev/DevOps/#/Kubernetes/YAML) returing 404 

**Suggestion:** Instead of a response, we can print _"Work in progress"_ to avoid further raise issue. @

**Comment by Pradumnasaraf** [comment]
Thank you. We have aware of this problem. We can't display the YAML file on the website.

I have fixed it in https://github.com/Pradumnasaraf/DevOps/commit/f3494ae339ecc1473387942dfbc9862624c70c7a now it will lead you to the repo.
