### ISSUE TITLE
[DOCS] Typo in Linux docs 

### ISSUE THREAD

**Issue by naveenkandula1** [Pradumnasaraf/DevOps#26]
### Description

Hi [Pradumnasaraf](https://github.com/Pradumnasaraf),

There is typo in the Linux docs. If you're okay I will do the contribution to fix it. It will be my first open source contribution. 

Thanks!

### Screenshots

![image](https://user-images.githubusercontent.com/121635604/209994664-e72875e3-6833-4e44-9c04-9ba6c13ba39a.png)

**Comment by Pradumnasaraf** [comment]
Yes, go ahead. If case of typos, feel free to raise PR without opening an issue.
