### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by mehrdadbn9** [Pradumnasaraf/DevOps#38]
### Description

Hi, 
is it possible to contribute at bash script part?
i would like to firstly add some more command like: Strict mode, File conditions, Default values, ...
would it be possible to add them firstly at readme and secondly write sh file of each of them?
i would add them base on your sources.

**Comment by mehrdadbn9** [comment]
@Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Hey, 

This repo is track my leranings. So I don't add stuff beforehand that I haven't learned. But still if you like to raise a PR, you can I will merge in a temp branch and merge it in near future.

**Comment by mehrdadbn9** [comment]
ok, thanks.
