### ISSUE TITLE
More Content and expatiation.

### ISSUE THREAD

**Issue by Shukla007** [Pradumnasaraf/DevOps#39]
### Description

Hey 👋 

I would like to contribute to this project and want to update the Linux notes section with different and in command section and its uses and many different learning resource for links and also want to add explanations screenshots.

**Comment by Pradumnasaraf** [comment]
Can you explain a little bit about what things you want to change and add?

**Comment by Shukla007** [comment]
I want to update the Linux resource by adding more leaning resources.

**Comment by Pradumnasaraf** [comment]
Sure, 1st you can share them here, after approval you can create a PR.

**Comment by Shukla007** [comment]
> Sure, 1st you can share them here, after approval you can create a PR.

Ok sure 👍👍

**Comment by Pradumnasaraf** [comment]
Due to inactivity on this issue for months I am closing it feel free to open a new one if you want.
