### ISSUE TITLE
[FEATURE] <Linux>

### ISSUE THREAD

**Issue by sumitNITS** [Pradumnasaraf/DevOps#50]
### Description

Hey @Pradumnasaraf,

I was thinking of improvising the Linux landing section by including Architecture components, Distributions, File systems, and their organizations along with the diagrams and so on.

Let me know your thoughts on it!

**Comment by Pradumnasaraf** [comment]
Hey, Yes go ahead. Keep it simple and short.

**Comment by sumitNITS** [comment]
Done. You can check now!
