### ISSUE TITLE
Adding contributors image in main readme file

### ISSUE THREAD

**Issue by Shyamjitripathi** [Pradumnasaraf/DevOps#57]
### Description
@Pradumnasaraf 
So, as a community driven project appreciating the contributor by mentioning them on the readme file will be a great idea. We can do this by using a dynamic image URL generated using "contrib.rocks" website, which generate a dynamic image URL for contributors of a project.

### Screenshots

![image](https://user-images.githubusercontent.com/59613166/232235009-8aa9c2a7-846e-4c05-acb6-ae09a8dc990f.png)

**Comment by Vivekgaddigi** [comment]
Good Idea

**Comment by Pradumnasaraf** [comment]
Hi there,

It's a great idea, but as the README file is deployed as the main page for the website, I'm not keen on duplicating the information on a separate page is necessary. Additionally, we already have a list of contributors on the left side.

Closing the issue, thank you for the effort.
