### ISSUE TITLE
[DOCS] modify /docker/readme.md

### ISSUE THREAD

**Issue by samyabrata-maji** [Pradumnasaraf/DevOps#60]
### Description

Line 62 of `/docker/readme` can be improved to something like:
"The `.dockerignore` file is used to specify the file and directories that are not copied when using the COPY command"

### Screenshots

<img width="533" alt="Screenshot 2023-05-08 220218" src="https://user-images.githubusercontent.com/116789799/236879139-dc301aac-f090-46f3-8dcf-61e3b0c777c1.png">

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue.

So you wan't to fix it?
