### ISSUE TITLE
[DOCS] Typo in Bash-Scripting/README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Pradumnasaraf/DevOps#63]
### Description

I have noticed two instances of the word "the" in the README.md file of the Bash-Scripting. I have attached a screenshot for your reference. I am eager to contribute to this repository and kindly request to be assigned to the task.

### Screenshots

![Screenshot (5)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/dc8095b9-197a-4090-812d-cf51fb5a9712)

**Comment by Pradumnasaraf** [comment]
Sure, go ahead
