### ISSUE TITLE
[DOCS] Typo's in Kubernetes/README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Pradumnasaraf/DevOps#68]
### Description

I have identified two errors in the Kubernetes/README.md file. I observed that the word "independent" is written as "indepent" and "container" is misspelled as "conatiner." I have included a screenshot for your reference. I am eager to resolve this issue and would appreciate being assigned to it.

### Screenshots

![Screenshot (8)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/f6395008-5647-4c04-b01e-83ca7877498d)

**Comment by Pradumnasaraf** [comment]
Go ahead, Shiva
