### ISSUE TITLE
[DOCS] Typo's in Docker/commands/README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Pradumnasaraf/DevOps#70]
### Description

I have identified two errors in the Docker/commands/README.md file. I observed that the word "customization" is written as "customiztaion" and "directly" is misspelled as "direclty". I have included a screenshot for your reference. I am eager to resolve this issue and would appreciate being assigned to it.

### Screenshots

![Screenshot (13)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/5657b8c9-506f-4246-a528-00db69a19b14)

**Comment by Pradumnasaraf** [comment]
Hey, thanks for your continuous effort. Yes, go ahead. 

Also, next time it would be great if use raise some issues and also let other new people fix that :)

**Comment by Shiva-Sai-ssb** [comment]
> Hey, thanks for your continuous effort. Yes, go ahead.
> 
> Also, next time it would be great if use raise some issues and also let other new people fix that :)

Sure, I will report any issues I find in the future and allow others to contribute to the project.
