### ISSUE TITLE
[DOCS] Typo's in Bash-Scripting/README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [Pradumnasaraf/DevOps#74]
### Description

I have identified the errors in the screenshots provided. You can label this as "good first issue" and assign it to new contributors. I'm okay with that.

### Screenshots

![Screenshot (14)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/9912b662-fe91-4826-b3c6-decdd59eac6a)

![Screenshot (15)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/cde58007-2467-4bff-90d8-291d7d95eb9c)

![Screenshot (16)](https://github.com/Pradumnasaraf/DevOps/assets/112751524/fe85757a-f703-4570-aff3-5cd3ab575d93)

**Comment by Sanjay-shankar** [comment]
I can sort it out. Please assign the request to me. Thank you!

**Comment by Pradumnasaraf** [comment]
Thank you for opening @Shiva-Sai-ssb. Yes, go ahead, @Sanjay-shankar

**Comment by Pradumnasaraf** [comment]
Fixed in #75
