### ISSUE TITLE
Readme Hyperlinks routing

### ISSUE THREAD

**Issue by Abhisheksainii** [Pradumnasaraf/DevOps#79]
### Description

Can we add a redirection to an new tab instead of the same tab when any hyperlink is opened (inside README file of a specific module)?

**Comment by Pradumnasaraf** [comment]
Great point. Would you like to worn on this?

**Comment by Abhisheksainii** [comment]
Why not?
Let me see what I can do.

**Comment by Abhisheksainii** [comment]
seems like Github markdown doesn't allow us to do so

**Comment by Pradumnasaraf** [comment]
Okay. Then let's close this issue.
