### ISSUE TITLE
Docker inside Docker volume Mount

### ISSUE THREAD

**Issue by yuva19102003** [Pradumnasaraf/DevOps#87]
### Description

docker volume mount command for mounting the host docker daemon to the docker container as a volume.
it will perform the CI tasks inside the docker container 
after the job gets finished 
it will automatically destroyed
if new jobs encounter means it create an new container and again mount it to the container
it will be used in continuous integration for jenkins. when using docker as a agent.

**Comment by Pradumnasaraf** [comment]
Hey,

You have raised the PR without confirmation. Check the contributing guidelines.

Merging PR for this time
