### ISSUE TITLE
[DOCS] Docs and resouces related to terraform

### ISSUE THREAD

**Issue by itsBaivab** [Pradumnasaraf/DevOps#96]
### Description

Should I add a page with docs and learning resources related to terrform?

**Comment by Pradumnasaraf** [comment]
Hey,

Thanks for opening the issue. Can you please share what you will add in the docs section?

**Comment by itsBaivab** [comment]
Starting with description 
Roadmap 
learning resources

**Comment by Pradumnasaraf** [comment]
Sure, go ahead. Thank you!
